name: Run on Linux/Ubuntu-latest | python 3.7->3.9
on: [push]
#defaults:
#  run:
#    working-directory: wrdir
jobs:
  #deploy:
  #  runs-on: windows-latest
  #  steps:
  #    - name: install readline
  #      run: python -m pip install readline
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest] #,windows-latest
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: pip Upgrade
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: get chromedriver
        run: bash chromium.sh
      - name: Get Posters
        run: python get_posters.py False
      - name: push commits
        run: |
          git add .
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git commit -am "update src/my_list.json"
          git push 
      - name: delete chromedriver
        run: |
          git add .
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git rm chromedriver
          git commit -m "remove chromedriver"
          git push 
      - name: delete chromedriver.zip
        run: |
          git add .
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git rm chromedriver.zip
          git commit -m "remove chromedriver.zip"
          git push 
